<?php

namespace News\RestBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends BaseRepository
{

  /**
   * Get Article
   *
   * @author Nguyen Nhu Tuan <tuanquynh0508@gmail.com>
   * @since 1.0
   * @param  int $id Id of Article
   * @return News\RestBundle\Entity\Article
   */
  public function getArticle($id)
  {
    return $this->find($id);
  }

  /**
   * Get Articles list
   *
   * @author Nguyen Nhu Tuan <tuanquynh0508@gmail.com>
   * @since 1.0
   * @param  integer $page        [description]
   * @param  integer $limit       [description]
   * @param  integer $category_id [description]
   * @return array
   */
  public function getArticles($page=1,$limit=10, $category_id=0)
  {
    $offset = ($page - 1) * $limit;
    $q = $this->getRepository()->createQueryBuilder('a');

    if(!empty($category_id)) {
      $q->leftJoin('a.category', 'c')
        ->where('c.categoryId = :category_id')
        ->setParameter('category_id', $category_id);
    }

    $q->setFirstResult($offset)
      ->setMaxResults($limit);

    $result = $q->getQuery()
                ->getResult();

    return $result;
  }
}
