<?php
namespace News\RestBundle\Repository;

use Doctrine\ORM\EntityManager as EntityManager;

/**
 * BaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository
{
  /**
   * [$em description]
   * @var [type]
   */
  protected $em;

  /**
   * [$bundle description]
   * @var String
   */
  protected $bundle;

  /**
   * [__construct description]
   * @param \Doctrine\ORM\EntityManager $em
   * @param String $bundle
   */
  public function __construct(EntityManager $em, $bundle)
  {
    $this->em = $em;
    $this->bundle = $bundle;
  }

  /**
   * Gets entity manager.
   *
   * @return \Doctrine\ORM\EntityManager
   */
  public function getEntityManager()
  {
    return $this->em;
  }

  /**
   * Gets a repository from current entity manager.
   *
   * @param string $name Entity shortcut name
   * @return \Doctrine\ORM\EntityRepository
   */
  public function getRepository()
  {
    $sClassPath = get_class($this);
    $aClass = explode('\\', $sClassPath);
    $sEntityName = str_replace('Repository', '', $aClass[count($aClass)-1]);
    return $this->getEntityManager()->getRepository($this->bundle.':'.$sEntityName);
  }

  ///////////////////////////////////////////////////////////////////////////////////

  /**
   * [find description]
   * @param  Integer $id
   * @return object
   */
  public function find($id) {
    return $this->getRepository()->find($id);
  }

  /**
   * [find description]
   * @return array
   */
  public function findAll() {
    return $this->getRepository()->findAll();
  }

}